name: Zip voix folder and upload on release

on:
  release:
    types: [created]

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Zip voix folder
        run: zip -r voix.zip voix
      - name: Upload voix.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: voix-chrome
          path: voix.zip
      - name: Upload voix.zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: voix.zip
          asset_name: voix.zip
          asset_content_type: application/zip